### ISSUE TITLE
Touchscreen udev rule not loaded automatically

### ISSUE THREAD

**Issue by petrmatula190** [wimpysworld/umpc-ubuntu#16]
I updated configuration on my Ubuntu 18.04.3 and my testing Ubuntu 19.04 and found one issue with load udev rule. 

On 18.04 (Xorg) i must reload kernel module after login, after touschsreen is rotated correctly.
`sudo modprobe -r goodix && sudo modprobe goodix`

On 19.04(Wayland/Xorg), touscreen not rotated in any case.

Anybody have the same problem? I am on latest HWE kernel on 18.04 (5.0 like Ubuntu 19.04, but 4.18/4.15 have the same problem).

**Comment by petrmatula190** [comment]
Some logs below
[dmesg_18.04.txt](https://github.com/wimpysworld/umpc-ubuntu/files/3492304/dmesg_18.04.txt)
[dmesg_19.04.txt](https://github.com/wimpysworld/umpc-ubuntu/files/3492305/dmesg_19.04.txt)
[udev_monitor_xorg_18.04.txt](https://github.com/wimpysworld/umpc-ubuntu/files/3492306/udev_monitor_xorg_18.04.txt)
[udev_monitor_xorg_19.04.txt](https://github.com/wimpysworld/umpc-ubuntu/files/3492307/udev_monitor_xorg_19.04.txt)
[xinput_wayland_19.04.txt](https://github.com/wimpysworld/umpc-ubuntu/files/3492308/xinput_wayland_19.04.txt)
[xinput_xorg_19.04.txt](https://github.com/wimpysworld/umpc-ubuntu/files/3492310/xinput_xorg_19.04.txt)

**Comment by petrmatula190** [comment]
I tried clean install and repined ISO is correct after install, but update broken it again.

**Comment by flexiondotorg** [comment]
Are you saying the issue is resolved?

**Comment by petrmatula190** [comment]
@flexiondotorg No, I am using old solution with 81-gpd-pocket2-touchscreen.conf on Ubuntu 18.04 and 19.04 too.

**Comment by flexiondotorg** [comment]
I can't reproduce this issue in the 19.10 image or upcoming 20.04.1 image for the GPD Pocket 2.
