### ISSUE TITLE
Topjoy Falcon flickery display if HDMI not connected

### ISSUE THREAD

**Issue by mulm** [wimpysworld/umpc-ubuntu#19]
Tried `ubuntu-mate-18.04.2-desktop-amd64-topjoy-falcon.iso` from https://ubuntu-mate.org/download/ which I believe to be based on these scripts.  If HDMI is plugged in, then all is well on both the HDMI output and device screen.  Without HDMI plugged in, screen flickers and is illegible and unusable.

Any ideas?  Is there a post-install step I'm missing?

**Comment by flexiondotorg** [comment]
This issue is resolved in the 19.10 image and the soon to released 20.04.1 image for the TopJoy Falcon.
