### ISSUE TITLE
Request update for GPD WIN MAX

### ISSUE THREAD

**Issue by a342191555** [wimpysworld/umpc-ubuntu#25]
Since the [GPD WIN MAX](https://www.indiegogo.com/projects/gpd-win-max-handheld-game-console-for-aaa-games#/) has been released, I've bought one. However,I've followed instructions for pocket2 to fix the screen rotation issue, but didn't work.

Besides, a YouTube video ( https://www.youtube.com/watch?v=PRdaV1cSOfo ) shows the screen can, in some way, work in the correct direction.

It seems nobody has discussed about the WIN MAX here and in reddit. So could anyone help me plz?

**Comment by flexiondotorg** [comment]
This information is probably useful to you. I don't have a Win Max to test with.

**Comment by a342191555** [comment]
Thanks, I'll test that

**Comment by flexiondotorg** [comment]
These scripts now support the GPD WIN Max :slightly_smiling_face:
