### ISSUE TITLE
OneMix3pro

### ISSUE THREAD

**Issue by jangorecki** [wimpysworld/umpc-ubuntu#26]
I installed Ubuntu 20.04 on onemix3pro and there are multiple issues (screen rotation, touch screen rotation, trackpoint precision, wifi disconnecting, low energy consumption mode Fn+Delete, fingerprint reader, Insert button functionality, fan control, ticking in left channel of audio connector output, multipoint touch screen like maps zoom in).
Could we please keep this issue open till there will be a dedicated repository/scripts to make Ubuntu working well on OneMix3pro? If one already exists and is maintained, please sharing a link. Thank you.
Note that there is also OneMix3pro platinium, AFAICT it is the same as pro but having better CPU, so scripts for pro should be applicable to pro platinium as well.
Machine is usable but many things could be improved.

**Comment by flexiondotorg** [comment]
Sorry, I don't have a OneMix3 Pro and therefore no means to work on this.

**Comment by jangorecki** [comment]
@flexiondotorg does that mean the issue must be closed then? couldn't it be left open till someone will link an active repo where such work is going to be undertaken?

**Comment by jangorecki** [comment]
any update on this one?
