### ISSUE TITLE
ubuntu mate touchscreen and popos 22.04 issues

### ISSUE THREAD

**Issue by hxc-gxc** [wimpysworld/umpc-ubuntu#48]
Hello there

I'm trying to install ubuntu mate on my GPD pocket 3.
If I respin an image like 22.04, when I am running the live USB everything works but if I install the distro everything works except touchscreen which seems to be inverted.
It is the same with the preset image Impish 21.10.
I tried to run umpc-ubuntu script many times after install but it does nothing more.
But I have to tell that when I'm using a stylus it's ok, the pointer is calibrated well, the issue is only when using the hand.

Do you have some ideas to help me fiix that please ?
thanks for your help !

best regards 

Thibault

**Comment by asherikov** [comment]
1. Ditch `99-gpd-pocket3-touch.rules`, looks like touchscreen works out of the box and rules are not applied in the live boot.
2. I have tears in Mate as well.

**Comment by hxc-gxc** [comment]
After a lot of searches I found this : 

`sudo gedit /etc/X11/xorg.conf.d/20-intel.conf`


2) Add this:

```
Section "Module"

Load "dri3"

EndSection



Section "Device"

Identifier "Intel Graphics"

Driver "intel"


Option "DRI" "3"

EndSection

```

3) Save & Reboot

Tears are not there anymore but it's not  usable, performance are awful, gpd pocket 3 is blowing and adding 2 monitors is not working too... I'm still stuck

**Comment by hxc-gxc** [comment]
I found a more easy way to get touchscreen correctly calibrated and working, without tears or performance issues by simply switching from X11 to Wayland on PopOs : 
- set WaylandEnable=true in /etc/gdm3/custom.conf
- run systemctl restart gdm.service - note that this will log you out and close all open programs
- at the log in screen, there is a small gear wheel on the bottom right side, choose "Pop on Wayland" instead of "Pop"

If your screen orientation isn't ok, go to settings > screens >  orientation and choose "Portrait on left"
